# Generated by Django 5.2.4 on 2025-07-07 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_x_player_y_alter_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attack',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='character',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='y',
            field=models.IntegerField(),
        ),
    ]
