# Generated by Django 5.2.4 on 2025-07-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_attack_player_character_player_hp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='player',
            name='character',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hp',
        ),
    ]
