# Generated by Django 5.2.4 on 2025-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_player_attack_remove_player_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attack',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='player',
            name='character',
            field=models.CharField(default='Blazer', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='player',
            name='zone',
            field=models.CharField(default='North', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
