# Generated by Django 5.2.4 on 2025-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_attack_player_character_player_hp_player_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='y',
            field=models.IntegerField(),
        ),
    ]
